# Generated by Django 6.0.3 on 2026-04-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_applicantprofile_interested_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('REVIEWING', 'Reviewing'), ('PAUSED', 'Paused'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),
        ),
    ]
