# Generated by Django 6.0.3 on 2026-04-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_internship_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='internship',
            name='preferred_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='internship',
            name='responsibilities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
